spring:
  redis:
    host: localhost
    port: 6379
    password: your_redis_password  # Optional if Redis is password protected
    timeout: 2000ms
    jedis:
      pool:
        max-active: 10  # Max active connections to Redis
        max-idle: 5     # Max idle connections to Redis
        min-idle: 1     # Min idle connections to Redis
jwt:
  secret-key: "jQS85QR7qrY5ROtdvR8CFEAOBKDTBZl2+TyHxc919UI="
