// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.helper;

public final class All {
  private All() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helper_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helper_StatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helper_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helper_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helper_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helper_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helper_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helper_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helper_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helper_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helper_ValidateTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helper_ValidateTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helper_ValidateTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helper_ValidateTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tall.proto\022\006helper\"\340\001\n\016StatusResponse\022$" +
      "\n\007Success\030\001 \001(\010B\n\010\000\030\000(\0000\000P\000R\007success\022\036\n\004" +
      "Code\030\002 \001(\tB\n\010\000\030\000(\0000\000P\000R\004code\022$\n\007Message\030" +
      "\003 \001(\tB\n\010\000\030\000(\0000\000P\000R\007message\022)\n\tErrorCode\030" +
      "\004 \001(\tB\n\010\000\030\000(\0000\000P\000R\nerror_code\022/\n\014ErrorMe" +
      "ssage\030\005 \001(\tB\n\010\000\030\000(\0000\000P\000R\rerror_message:\006" +
      "\010\000\020\000\030\000\"e\n\014LoginRequest\022&\n\010Username\030\001 \001(\t" +
      "B\n\010\000\030\000(\0000\000P\000R\010username\022%\n\007LoginID\030\002 \001(\tB" +
      "\n\010\000\030\000(\0000\000P\000R\010login_id:\006\010\000\020\000\030\000\"\206\001\n\rLoginR" +
      "esponse\022K\n\016StatusResponse\030\001 \001(\0132\026.helper" +
      ".StatusResponseB\n\010\000\030\000(\0000\000P\000R\017status_resp" +
      "onse\022 \n\005Token\030\002 \001(\tB\n\010\000\030\000(\0000\000P\000R\005token:\006" +
      "\010\000\020\000\030\000\"9\n\rLogoutRequest\022 \n\005Token\030\001 \001(\tB\n" +
      "\010\000\030\000(\0000\000P\000R\005token:\006\010\000\020\000\030\000\"e\n\016LogoutRespo" +
      "nse\022K\n\016StatusResponse\030\001 \001(\0132\026.helper.Sta" +
      "tusResponseB\n\010\000\030\000(\0000\000P\000R\017status_response" +
      ":\006\010\000\020\000\030\000\"@\n\024ValidateTokenRequest\022 \n\005Toke" +
      "n\030\001 \001(\tB\n\010\000\030\000(\0000\000P\000R\005token:\006\010\000\020\000\030\000\"\242\001\n\025V" +
      "alidateTokenResponse\022K\n\016StatusResponse\030\001" +
      " \001(\0132\026.helper.StatusResponseB\n\010\000\030\000(\0000\000P\000" +
      "R\017status_response\0224\n\004Data\030\002 \001(\0132\024.helper" +
      ".LoginRequestB\n\010\000\030\000(\0000\000P\000R\004data:\006\010\000\020\000\030\0002" +
      "\355\001\n\021AuthHelperService\022<\n\005Login\022\024.helper." +
      "LoginRequest\032\025.helper.LoginResponse\"\006\210\002\000" +
      "\220\002\000\022?\n\006Logout\022\025.helper.LogoutRequest\032\026.h" +
      "elper.LogoutResponse\"\006\210\002\000\220\002\000\022T\n\rValidate" +
      "Token\022\034.helper.ValidateTokenRequest\032\035.he" +
      "lper.ValidateTokenResponse\"\006\210\002\000\220\002\000\032\003\210\002\000B" +
      "M\n\032com.example.gunk.v1.helperH\001P\001Z\026myapp" +
      "/v1/helper;helper\200\001\000\210\001\000\220\001\000\270\001\000\330\001\000\370\001\001\320\002\000b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helper_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helper_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helper_StatusResponse_descriptor,
        new java.lang.String[] { "Success", "Code", "Message", "ErrorCode", "ErrorMessage", });
    internal_static_helper_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helper_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helper_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "LoginID", });
    internal_static_helper_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helper_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helper_LoginResponse_descriptor,
        new java.lang.String[] { "StatusResponse", "Token", });
    internal_static_helper_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helper_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helper_LogoutRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_helper_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helper_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helper_LogoutResponse_descriptor,
        new java.lang.String[] { "StatusResponse", });
    internal_static_helper_ValidateTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_helper_ValidateTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helper_ValidateTokenRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_helper_ValidateTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_helper_ValidateTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helper_ValidateTokenResponse_descriptor,
        new java.lang.String[] { "StatusResponse", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
