// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.helper;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helper.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasStatusResponse();
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.StatusResponse getStatusResponse();
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.StatusResponseOrBuilder getStatusResponseOrBuilder();

  /**
   * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getToken();
  /**
   * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
