// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.helper;

/**
 * Protobuf type {@code helper.LoginResponse}
 */
public  final class LoginResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helper.LoginResponse)
    LoginResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoginResponse.newBuilder() to construct.
  private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoginResponse() {
    token_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LoginResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LoginResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.gunk.v1.helper.StatusResponse.Builder subBuilder = null;
            if (statusResponse_ != null) {
              subBuilder = statusResponse_.toBuilder();
            }
            statusResponse_ = input.readMessage(com.example.gunk.v1.helper.StatusResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(statusResponse_);
              statusResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.gunk.v1.helper.All.internal_static_helper_LoginResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.gunk.v1.helper.All.internal_static_helper_LoginResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.gunk.v1.helper.LoginResponse.class, com.example.gunk.v1.helper.LoginResponse.Builder.class);
  }

  public static final int STATUSRESPONSE_FIELD_NUMBER = 1;
  private com.example.gunk.v1.helper.StatusResponse statusResponse_;
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public boolean hasStatusResponse() {
    return statusResponse_ != null;
  }
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public com.example.gunk.v1.helper.StatusResponse getStatusResponse() {
    return statusResponse_ == null ? com.example.gunk.v1.helper.StatusResponse.getDefaultInstance() : statusResponse_;
  }
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public com.example.gunk.v1.helper.StatusResponseOrBuilder getStatusResponseOrBuilder() {
    return getStatusResponse();
  }

  public static final int TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object token_;
  /**
   * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (statusResponse_ != null) {
      output.writeMessage(1, getStatusResponse());
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (statusResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatusResponse());
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.gunk.v1.helper.LoginResponse)) {
      return super.equals(obj);
    }
    com.example.gunk.v1.helper.LoginResponse other = (com.example.gunk.v1.helper.LoginResponse) obj;

    if (hasStatusResponse() != other.hasStatusResponse()) return false;
    if (hasStatusResponse()) {
      if (!getStatusResponse()
          .equals(other.getStatusResponse())) return false;
    }
    if (!getToken()
        .equals(other.getToken())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatusResponse()) {
      hash = (37 * hash) + STATUSRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusResponse().hashCode();
    }
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.gunk.v1.helper.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.gunk.v1.helper.LoginResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helper.LoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helper.LoginResponse)
      com.example.gunk.v1.helper.LoginResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.gunk.v1.helper.All.internal_static_helper_LoginResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.gunk.v1.helper.All.internal_static_helper_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.gunk.v1.helper.LoginResponse.class, com.example.gunk.v1.helper.LoginResponse.Builder.class);
    }

    // Construct using com.example.gunk.v1.helper.LoginResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusResponseBuilder_ == null) {
        statusResponse_ = null;
      } else {
        statusResponse_ = null;
        statusResponseBuilder_ = null;
      }
      token_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.gunk.v1.helper.All.internal_static_helper_LoginResponse_descriptor;
    }

    @java.lang.Override
    public com.example.gunk.v1.helper.LoginResponse getDefaultInstanceForType() {
      return com.example.gunk.v1.helper.LoginResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.gunk.v1.helper.LoginResponse build() {
      com.example.gunk.v1.helper.LoginResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.gunk.v1.helper.LoginResponse buildPartial() {
      com.example.gunk.v1.helper.LoginResponse result = new com.example.gunk.v1.helper.LoginResponse(this);
      if (statusResponseBuilder_ == null) {
        result.statusResponse_ = statusResponse_;
      } else {
        result.statusResponse_ = statusResponseBuilder_.build();
      }
      result.token_ = token_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.gunk.v1.helper.LoginResponse) {
        return mergeFrom((com.example.gunk.v1.helper.LoginResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.gunk.v1.helper.LoginResponse other) {
      if (other == com.example.gunk.v1.helper.LoginResponse.getDefaultInstance()) return this;
      if (other.hasStatusResponse()) {
        mergeStatusResponse(other.getStatusResponse());
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.gunk.v1.helper.LoginResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.gunk.v1.helper.LoginResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.gunk.v1.helper.StatusResponse statusResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.gunk.v1.helper.StatusResponse, com.example.gunk.v1.helper.StatusResponse.Builder, com.example.gunk.v1.helper.StatusResponseOrBuilder> statusResponseBuilder_;
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public boolean hasStatusResponse() {
      return statusResponseBuilder_ != null || statusResponse_ != null;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.StatusResponse getStatusResponse() {
      if (statusResponseBuilder_ == null) {
        return statusResponse_ == null ? com.example.gunk.v1.helper.StatusResponse.getDefaultInstance() : statusResponse_;
      } else {
        return statusResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStatusResponse(com.example.gunk.v1.helper.StatusResponse value) {
      if (statusResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        statusResponse_ = value;
        onChanged();
      } else {
        statusResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStatusResponse(
        com.example.gunk.v1.helper.StatusResponse.Builder builderForValue) {
      if (statusResponseBuilder_ == null) {
        statusResponse_ = builderForValue.build();
        onChanged();
      } else {
        statusResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeStatusResponse(com.example.gunk.v1.helper.StatusResponse value) {
      if (statusResponseBuilder_ == null) {
        if (statusResponse_ != null) {
          statusResponse_ =
            com.example.gunk.v1.helper.StatusResponse.newBuilder(statusResponse_).mergeFrom(value).buildPartial();
        } else {
          statusResponse_ = value;
        }
        onChanged();
      } else {
        statusResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearStatusResponse() {
      if (statusResponseBuilder_ == null) {
        statusResponse_ = null;
        onChanged();
      } else {
        statusResponse_ = null;
        statusResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.StatusResponse.Builder getStatusResponseBuilder() {
      
      onChanged();
      return getStatusResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.StatusResponseOrBuilder getStatusResponseOrBuilder() {
      if (statusResponseBuilder_ != null) {
        return statusResponseBuilder_.getMessageOrBuilder();
      } else {
        return statusResponse_ == null ?
            com.example.gunk.v1.helper.StatusResponse.getDefaultInstance() : statusResponse_;
      }
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.gunk.v1.helper.StatusResponse, com.example.gunk.v1.helper.StatusResponse.Builder, com.example.gunk.v1.helper.StatusResponseOrBuilder> 
        getStatusResponseFieldBuilder() {
      if (statusResponseBuilder_ == null) {
        statusResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.gunk.v1.helper.StatusResponse, com.example.gunk.v1.helper.StatusResponse.Builder, com.example.gunk.v1.helper.StatusResponseOrBuilder>(
                getStatusResponse(),
                getParentForChildren(),
                isClean());
        statusResponse_ = null;
      }
      return statusResponseBuilder_;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <code>string Token = 2[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helper.LoginResponse)
  }

  // @@protoc_insertion_point(class_scope:helper.LoginResponse)
  private static final com.example.gunk.v1.helper.LoginResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.gunk.v1.helper.LoginResponse();
  }

  public static com.example.gunk.v1.helper.LoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginResponse>
      PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
    @java.lang.Override
    public LoginResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LoginResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoginResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.gunk.v1.helper.LoginResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

