// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.helper;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helper.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Username = 1[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string Username = 1[json_name = "username", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string LoginID = 2[json_name = "login_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getLoginID();
  /**
   * <code>string LoginID = 2[json_name = "login_id", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getLoginIDBytes();
}
