// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.helper;

public interface LogoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helper.LogoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasStatusResponse();
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.StatusResponse getStatusResponse();
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.StatusResponseOrBuilder getStatusResponseOrBuilder();
}
