// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.helper;

/**
 * Protobuf type {@code helper.ValidateTokenResponse}
 */
public  final class ValidateTokenResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helper.ValidateTokenResponse)
    ValidateTokenResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidateTokenResponse.newBuilder() to construct.
  private ValidateTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidateTokenResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValidateTokenResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValidateTokenResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.gunk.v1.helper.StatusResponse.Builder subBuilder = null;
            if (statusResponse_ != null) {
              subBuilder = statusResponse_.toBuilder();
            }
            statusResponse_ = input.readMessage(com.example.gunk.v1.helper.StatusResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(statusResponse_);
              statusResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.example.gunk.v1.helper.LoginRequest.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.example.gunk.v1.helper.LoginRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.gunk.v1.helper.All.internal_static_helper_ValidateTokenResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.gunk.v1.helper.All.internal_static_helper_ValidateTokenResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.gunk.v1.helper.ValidateTokenResponse.class, com.example.gunk.v1.helper.ValidateTokenResponse.Builder.class);
  }

  public static final int STATUSRESPONSE_FIELD_NUMBER = 1;
  private com.example.gunk.v1.helper.StatusResponse statusResponse_;
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public boolean hasStatusResponse() {
    return statusResponse_ != null;
  }
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public com.example.gunk.v1.helper.StatusResponse getStatusResponse() {
    return statusResponse_ == null ? com.example.gunk.v1.helper.StatusResponse.getDefaultInstance() : statusResponse_;
  }
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public com.example.gunk.v1.helper.StatusResponseOrBuilder getStatusResponseOrBuilder() {
    return getStatusResponse();
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.example.gunk.v1.helper.LoginRequest data_;
  /**
   * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public com.example.gunk.v1.helper.LoginRequest getData() {
    return data_ == null ? com.example.gunk.v1.helper.LoginRequest.getDefaultInstance() : data_;
  }
  /**
   * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  public com.example.gunk.v1.helper.LoginRequestOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (statusResponse_ != null) {
      output.writeMessage(1, getStatusResponse());
    }
    if (data_ != null) {
      output.writeMessage(2, getData());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (statusResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatusResponse());
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.gunk.v1.helper.ValidateTokenResponse)) {
      return super.equals(obj);
    }
    com.example.gunk.v1.helper.ValidateTokenResponse other = (com.example.gunk.v1.helper.ValidateTokenResponse) obj;

    if (hasStatusResponse() != other.hasStatusResponse()) return false;
    if (hasStatusResponse()) {
      if (!getStatusResponse()
          .equals(other.getStatusResponse())) return false;
    }
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatusResponse()) {
      hash = (37 * hash) + STATUSRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusResponse().hashCode();
    }
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.gunk.v1.helper.ValidateTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.gunk.v1.helper.ValidateTokenResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helper.ValidateTokenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helper.ValidateTokenResponse)
      com.example.gunk.v1.helper.ValidateTokenResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.gunk.v1.helper.All.internal_static_helper_ValidateTokenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.gunk.v1.helper.All.internal_static_helper_ValidateTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.gunk.v1.helper.ValidateTokenResponse.class, com.example.gunk.v1.helper.ValidateTokenResponse.Builder.class);
    }

    // Construct using com.example.gunk.v1.helper.ValidateTokenResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusResponseBuilder_ == null) {
        statusResponse_ = null;
      } else {
        statusResponse_ = null;
        statusResponseBuilder_ = null;
      }
      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.gunk.v1.helper.All.internal_static_helper_ValidateTokenResponse_descriptor;
    }

    @java.lang.Override
    public com.example.gunk.v1.helper.ValidateTokenResponse getDefaultInstanceForType() {
      return com.example.gunk.v1.helper.ValidateTokenResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.gunk.v1.helper.ValidateTokenResponse build() {
      com.example.gunk.v1.helper.ValidateTokenResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.gunk.v1.helper.ValidateTokenResponse buildPartial() {
      com.example.gunk.v1.helper.ValidateTokenResponse result = new com.example.gunk.v1.helper.ValidateTokenResponse(this);
      if (statusResponseBuilder_ == null) {
        result.statusResponse_ = statusResponse_;
      } else {
        result.statusResponse_ = statusResponseBuilder_.build();
      }
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.gunk.v1.helper.ValidateTokenResponse) {
        return mergeFrom((com.example.gunk.v1.helper.ValidateTokenResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.gunk.v1.helper.ValidateTokenResponse other) {
      if (other == com.example.gunk.v1.helper.ValidateTokenResponse.getDefaultInstance()) return this;
      if (other.hasStatusResponse()) {
        mergeStatusResponse(other.getStatusResponse());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.gunk.v1.helper.ValidateTokenResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.gunk.v1.helper.ValidateTokenResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.gunk.v1.helper.StatusResponse statusResponse_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.gunk.v1.helper.StatusResponse, com.example.gunk.v1.helper.StatusResponse.Builder, com.example.gunk.v1.helper.StatusResponseOrBuilder> statusResponseBuilder_;
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public boolean hasStatusResponse() {
      return statusResponseBuilder_ != null || statusResponse_ != null;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.StatusResponse getStatusResponse() {
      if (statusResponseBuilder_ == null) {
        return statusResponse_ == null ? com.example.gunk.v1.helper.StatusResponse.getDefaultInstance() : statusResponse_;
      } else {
        return statusResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStatusResponse(com.example.gunk.v1.helper.StatusResponse value) {
      if (statusResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        statusResponse_ = value;
        onChanged();
      } else {
        statusResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStatusResponse(
        com.example.gunk.v1.helper.StatusResponse.Builder builderForValue) {
      if (statusResponseBuilder_ == null) {
        statusResponse_ = builderForValue.build();
        onChanged();
      } else {
        statusResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeStatusResponse(com.example.gunk.v1.helper.StatusResponse value) {
      if (statusResponseBuilder_ == null) {
        if (statusResponse_ != null) {
          statusResponse_ =
            com.example.gunk.v1.helper.StatusResponse.newBuilder(statusResponse_).mergeFrom(value).buildPartial();
        } else {
          statusResponse_ = value;
        }
        onChanged();
      } else {
        statusResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearStatusResponse() {
      if (statusResponseBuilder_ == null) {
        statusResponse_ = null;
        onChanged();
      } else {
        statusResponse_ = null;
        statusResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.StatusResponse.Builder getStatusResponseBuilder() {
      
      onChanged();
      return getStatusResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.StatusResponseOrBuilder getStatusResponseOrBuilder() {
      if (statusResponseBuilder_ != null) {
        return statusResponseBuilder_.getMessageOrBuilder();
      } else {
        return statusResponse_ == null ?
            com.example.gunk.v1.helper.StatusResponse.getDefaultInstance() : statusResponse_;
      }
    }
    /**
     * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.gunk.v1.helper.StatusResponse, com.example.gunk.v1.helper.StatusResponse.Builder, com.example.gunk.v1.helper.StatusResponseOrBuilder> 
        getStatusResponseFieldBuilder() {
      if (statusResponseBuilder_ == null) {
        statusResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.gunk.v1.helper.StatusResponse, com.example.gunk.v1.helper.StatusResponse.Builder, com.example.gunk.v1.helper.StatusResponseOrBuilder>(
                getStatusResponse(),
                getParentForChildren(),
                isClean());
        statusResponse_ = null;
      }
      return statusResponseBuilder_;
    }

    private com.example.gunk.v1.helper.LoginRequest data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.gunk.v1.helper.LoginRequest, com.example.gunk.v1.helper.LoginRequest.Builder, com.example.gunk.v1.helper.LoginRequestOrBuilder> dataBuilder_;
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.LoginRequest getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.example.gunk.v1.helper.LoginRequest.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setData(com.example.gunk.v1.helper.LoginRequest value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setData(
        com.example.gunk.v1.helper.LoginRequest.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder mergeData(com.example.gunk.v1.helper.LoginRequest value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.example.gunk.v1.helper.LoginRequest.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.LoginRequest.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public com.example.gunk.v1.helper.LoginRequestOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.example.gunk.v1.helper.LoginRequest.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.gunk.v1.helper.LoginRequest, com.example.gunk.v1.helper.LoginRequest.Builder, com.example.gunk.v1.helper.LoginRequestOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.gunk.v1.helper.LoginRequest, com.example.gunk.v1.helper.LoginRequest.Builder, com.example.gunk.v1.helper.LoginRequestOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helper.ValidateTokenResponse)
  }

  // @@protoc_insertion_point(class_scope:helper.ValidateTokenResponse)
  private static final com.example.gunk.v1.helper.ValidateTokenResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.gunk.v1.helper.ValidateTokenResponse();
  }

  public static com.example.gunk.v1.helper.ValidateTokenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidateTokenResponse>
      PARSER = new com.google.protobuf.AbstractParser<ValidateTokenResponse>() {
    @java.lang.Override
    public ValidateTokenResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValidateTokenResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValidateTokenResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidateTokenResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.gunk.v1.helper.ValidateTokenResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

