// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.helper;

public interface ValidateTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helper.ValidateTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasStatusResponse();
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.StatusResponse getStatusResponse();
  /**
   * <code>.helper.StatusResponse StatusResponse = 1[json_name = "status_response", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.StatusResponseOrBuilder getStatusResponseOrBuilder();

  /**
   * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean hasData();
  /**
   * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.LoginRequest getData();
  /**
   * <code>.helper.LoginRequest Data = 2[json_name = "data", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.example.gunk.v1.helper.LoginRequestOrBuilder getDataOrBuilder();
}
