// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.auth;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool Success = 1[json_name = "success", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  boolean getSuccess();

  /**
   * <code>string Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getCode();
  /**
   * <code>string Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string Message = 3[json_name = "message", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string Message = 3[json_name = "message", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string ErrorCode = 4[json_name = "error_code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getErrorCode();
  /**
   * <code>string ErrorCode = 4[json_name = "error_code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>string ErrorMessage = 5[json_name = "error_message", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string ErrorMessage = 5[json_name = "error_message", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
