// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.auth;

public interface ValidateTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.ValidateTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Token = 1[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getToken();
  /**
   * <code>string Token = 1[json_name = "token", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
