// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package com.example.gunk.v1.auth;

public final class All {
  private All() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_StatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_StatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_ValidateTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_ValidateTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_ValidateTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_ValidateTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tall.proto\022\004auth\"\340\001\n\016StatusResponse\022$\n\007" +
      "Success\030\001 \001(\010B\n\010\000\030\000(\0000\000P\000R\007success\022\036\n\004Co" +
      "de\030\002 \001(\tB\n\010\000\030\000(\0000\000P\000R\004code\022$\n\007Message\030\003 " +
      "\001(\tB\n\010\000\030\000(\0000\000P\000R\007message\022)\n\tErrorCode\030\004 " +
      "\001(\tB\n\010\000\030\000(\0000\000P\000R\nerror_code\022/\n\014ErrorMess" +
      "age\030\005 \001(\tB\n\010\000\030\000(\0000\000P\000R\rerror_message:\006\010\000" +
      "\020\000\030\000\"e\n\014LoginRequest\022&\n\010Username\030\001 \001(\tB\n" +
      "\010\000\030\000(\0000\000P\000R\010username\022%\n\007LoginID\030\002 \001(\tB\n\010" +
      "\000\030\000(\0000\000P\000R\010login_id:\006\010\000\020\000\030\000\"\204\001\n\rLoginRes" +
      "ponse\022I\n\016StatusResponse\030\001 \001(\0132\024.auth.Sta" +
      "tusResponseB\n\010\000\030\000(\0000\000P\000R\017status_response" +
      "\022 \n\005Token\030\002 \001(\tB\n\010\000\030\000(\0000\000P\000R\005token:\006\010\000\020\000" +
      "\030\000\"9\n\rLogoutRequest\022 \n\005Token\030\001 \001(\tB\n\010\000\030\000" +
      "(\0000\000P\000R\005token:\006\010\000\020\000\030\000\"c\n\016LogoutResponse\022" +
      "I\n\016StatusResponse\030\001 \001(\0132\024.auth.StatusRes" +
      "ponseB\n\010\000\030\000(\0000\000P\000R\017status_response:\006\010\000\020\000" +
      "\030\000\"@\n\024ValidateTokenRequest\022 \n\005Token\030\001 \001(" +
      "\tB\n\010\000\030\000(\0000\000P\000R\005token:\006\010\000\020\000\030\000\"\236\001\n\025Validat" +
      "eTokenResponse\022I\n\016StatusResponse\030\001 \001(\0132\024" +
      ".auth.StatusResponseB\n\010\000\030\000(\0000\000P\000R\017status" +
      "_response\0222\n\004Data\030\002 \001(\0132\022.auth.LoginRequ" +
      "estB\n\010\000\030\000(\0000\000P\000R\004data:\006\010\000\020\000\030\0002\333\001\n\013AuthSe" +
      "rvice\0228\n\005Login\022\022.auth.LoginRequest\032\023.aut" +
      "h.LoginResponse\"\006\210\002\000\220\002\000\022;\n\006Logout\022\023.auth" +
      ".LogoutRequest\032\024.auth.LogoutResponse\"\006\210\002" +
      "\000\220\002\000\022P\n\rValidateToken\022\032.auth.ValidateTok" +
      "enRequest\032\033.auth.ValidateTokenResponse\"\006" +
      "\210\002\000\220\002\000\032\003\210\002\000BG\n\030com.example.gunk.v1.authH" +
      "\001P\001Z\022myapp/v1/auth;auth\200\001\000\210\001\000\220\001\000\270\001\000\330\001\000\370\001" +
      "\001\320\002\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_auth_StatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_StatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_StatusResponse_descriptor,
        new java.lang.String[] { "Success", "Code", "Message", "ErrorCode", "ErrorMessage", });
    internal_static_auth_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "LoginID", });
    internal_static_auth_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_auth_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_LoginResponse_descriptor,
        new java.lang.String[] { "StatusResponse", "Token", });
    internal_static_auth_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_auth_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_LogoutRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_auth_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_auth_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_LogoutResponse_descriptor,
        new java.lang.String[] { "StatusResponse", });
    internal_static_auth_ValidateTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_auth_ValidateTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_ValidateTokenRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_auth_ValidateTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_auth_ValidateTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_ValidateTokenResponse_descriptor,
        new java.lang.String[] { "StatusResponse", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
